// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_qByEKlckVvILY3SyjA97drSvJrEYGE',
    appId: '1:707365312544:web:9264bcd34059b059d8c445',
    messagingSenderId: '707365312544',
    projectId: 'socialmediapp-a4434',
    authDomain: 'socialmediapp-a4434.firebaseapp.com',
    storageBucket: 'socialmediapp-a4434.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMF2hGnYLFnnCK7_p8coILGJ5j_NCH1k',
    appId: '1:707365312544:android:961c4fc17f0af8f3d8c445',
    messagingSenderId: '707365312544',
    projectId: 'socialmediapp-a4434',
    storageBucket: 'socialmediapp-a4434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7W6HGIQUk8I9brb5KQ6_V-EPxaVJr-rs',
    appId: '1:707365312544:ios:466b316132f3e2efd8c445',
    messagingSenderId: '707365312544',
    projectId: 'socialmediapp-a4434',
    storageBucket: 'socialmediapp-a4434.appspot.com',
    iosClientId: '707365312544-7pfmf772q6t1blskrdrblk4vlde3ijgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaAppTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7W6HGIQUk8I9brb5KQ6_V-EPxaVJr-rs',
    appId: '1:707365312544:ios:43d5334c73819206d8c445',
    messagingSenderId: '707365312544',
    projectId: 'socialmediapp-a4434',
    storageBucket: 'socialmediapp-a4434.appspot.com',
    iosClientId: '707365312544-60dfl5lsl0r10ppm7lj869rkvu1df4s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaAppTutorial.RunnerTests',
  );
}
